# Generated by Django 6.1 on 2026-08-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'lesson completion',
                'verbose_name_plural': 'lesson completions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons', models.PositiveIntegerField(default=0, verbose_name='completed lessons')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='total lessons')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='percent')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.course')),
            ],
            options={
                'verbose_name': 'course progress',
                'verbose_name_plural': 'course progress records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
