# Generated by Django 6.1 on 2026-08-16 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_course_progress_per_student'),
        ),
        migrations.AddConstraint(
            model_name='lessoncompletion',
            constraint=models.UniqueConstraint(fields=('student', 'lesson'), name='unique_lesson_completion_per_student'),
        ),
    ]
